"""Server-side cache for PlacementState round-trips.

Per ``docs/SPEC_Schematic_Placement.md`` § Stateful vs stateless modes.

Layout:
  ~/.cache/kicad-mcp/placement_states/<schematic_hash>/<state_id>.json

The ``schematic_hash`` directory is the first 16 hex chars of
``sha256(schematic_path)`` — a stable per-schematic shard so per-schematic
operations (``find_latest_for_schematic``, ``_evict_lru_for_schematic``)
only scan that schematic's own files instead of the whole cache. With 200
schematics × 5 states each (= 1000 files), the previous flat layout
made every ``suggest`` call do two full-cache JSON parses; now it's
a glob of ≤5 files in one subdirectory.

``load_state(state_id)`` doesn't carry the schematic context, so it
short-circuits by globbing ``*/<state_id>.json`` and checking ``exists()``
on each candidate — O(num_shards) ``stat`` syscalls but no file reads
until a match is found.

Retention:
  - 5 states per schematic max (LRU by mtime, eviction on save)
  - 30-day expiry from mtime (whole-cache sweep on save, throttled to at
    most once per _SWEEP_INTERVAL_SECONDS -- expiry is ALSO enforced
    independently at read time, so throttling only delays physical disk
    reclaim, never serves an expired entry)

The JSON file is the source of truth — there is no in-memory cache on
top. After a server restart, a ``state_id`` remains valid as long as
its JSON file exists. Save/load failures fall back gracefully (no
exception leaks to the calling tool).
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import logging
import os
import re
import time
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Override-able for tests.
CACHE_DIR_ENV = "KICAD_MCP_PLACEMENT_CACHE_DIR"
_DEFAULT_CACHE_DIR = Path.home() / ".cache" / "kicad-mcp" / "placement_states"

MAX_STATES_PER_SCHEMATIC = 5
DEFAULT_MAX_AGE_DAYS = 30

# _sweep_expired() walks EVERY shard (d.glob("*/*.json")) -- unlike the
# per-schematic eviction right above it, which only touches the shard the
# save just wrote to. Running that whole-cache walk on every single
# save_state() call defeated the point of sharding for this portion of the
# call: with a 30-day expiry window there is no correctness reason to sweep
# more than occasionally. _expired() is checked independently at read time
# (find_latest_for_schematic/load_state), so a file that lingers a bit
# longer than the interval below is never actually SERVED past its expiry
# -- throttling only delays physical disk reclaim, not correctness.
# finding #29 of the 2026-09-23 full review's Phase 1 pass.
_SWEEP_INTERVAL_SECONDS = 3600  # 1 hour
_last_swept_at = 0.0

# State IDs are generated by ``secrets.token_hex(8)`` — exactly 16 hex chars.
# We validate caller-supplied state_ids against this shape before joining them
# into a filesystem path: an unvalidated id (e.g. ``"../../etc/passwd"`` or
# ``"/etc/hosts"``) would let Path() escape the cache directory and let
# ``load_state`` read arbitrary JSON files. Keep this regex anchored.
_STATE_ID_RE = re.compile(r"^[0-9a-f]{16}$")


def _valid_state_id(state_id: str) -> bool:
    return isinstance(state_id, str) and bool(_STATE_ID_RE.match(state_id))


def cache_dir() -> Path:
    """Resolved cache directory. Honors KICAD_MCP_PLACEMENT_CACHE_DIR
    so tests can isolate without touching the user's real cache."""
    override = os.environ.get(CACHE_DIR_ENV)
    if override:
        return Path(override)
    return _DEFAULT_CACHE_DIR


def _ensure_dir() -> Path:
    d = cache_dir()
    d.mkdir(parents=True, exist_ok=True)
    return d


def _schematic_shard(schematic_path: str) -> str:
    """Stable per-schematic shard name. First 16 hex chars of
    sha256(normalized schematic_path) — enough entropy that path-collision is
    vanishingly unlikely within a single cache.

    The path is normalized via ``str(Path(...))`` (lexical: collapses ``./``,
    doubled slashes and trailing slashes) so that ``suggest`` and ``apply``
    derive the same shard for the same logical path. ``suggest`` already
    stores ``str(Path(...))``, so normalizing here is idempotent for saved
    states — it only fixes ``apply``'s lookup when the caller passes a
    non-normalized but equivalent path. This is the single source of truth
    for the shard key; no caller normalizes on its own."""
    if not schematic_path:
        # Every caller with a falsy schematic_path collapses into this ONE
        # shared shard -- two unrelated callers that both omit it would
        # contend for the same MAX_STATES_PER_SCHEMATIC=5 LRU slot, so one
        # caller's save could evict another's with no relation between them.
        # Logged (not restructured into per-caller buckets) since there's no
        # caller identity to shard on without a schematic_path in the first
        # place -- this makes the collision visible if it ever actually
        # matters in practice, rather than silent either way.
        logger.debug("Falsy schematic_path -- using shared '_unknown' cache shard")
        return "_unknown"
    normalized = str(Path(schematic_path))
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()[:16]


def _shard_dir(schematic_path: str) -> Path:
    return cache_dir() / _schematic_shard(schematic_path)


def save_state(state: dict[str, Any]) -> str | None:
    """Persist a PlacementState to disk. Returns the state_id on success,
    ``None`` on disk-write failure.

    Returning ``None`` (rather than always returning the id and silently
    eating the OSError) gives the caller a signal that the cache write
    failed — important because a state_id the caller stores but can never
    load back is worse than no state_id at all.

    Also runs eviction (per-schematic LRU, every save) and an expiry sweep
    (whole-cache, throttled to at most once per _SWEEP_INTERVAL_SECONDS) so
    the cache doesn't grow unbounded.
    """
    state_id = state.get("state_id")
    if not state_id:
        raise ValueError("state must have a state_id")
    if not _valid_state_id(state_id):
        # Defense in depth: state_ids are server-generated, so a non-conforming
        # id reaching save_state is a bug, not user input — fail loudly.
        raise ValueError(
            f"state_id must be 16 lowercase hex chars; got {state_id!r}"
        )
    try:
        _ensure_dir()
        schematic_path = state.get("schematic_path", "")
        shard = _shard_dir(schematic_path)
        shard.mkdir(parents=True, exist_ok=True)
        path = shard / f"{state_id}.json"
        path.write_text(json.dumps(state, indent=2))
        _evict_lru_for_schematic(schematic_path)
        global _last_swept_at
        now = time.time()
        if now - _last_swept_at >= _SWEEP_INTERVAL_SECONDS:
            _sweep_expired()
            _last_swept_at = now
    except OSError as e:
        logger.warning("placement cache save failed: %s", e)
        return None
    return str(state_id)


def load_state(state_id: str) -> dict[str, Any] | None:
    """Read a cached state. Returns None on miss, on parse error, if the
    file is older than the expiry window, or if the state_id is malformed.

    Validating ``state_id`` against ``_STATE_ID_RE`` here is the security
    boundary: it prevents a caller-supplied id like ``"../../etc/passwd"``
    or ``"/etc/hosts"`` from escaping the cache directory through Path
    concatenation. Treat malformed ids as misses, not errors.
    """
    if not _valid_state_id(state_id):
        return None
    try:
        path = _find_state_file(state_id)
        if path is None:
            return None
        if _expired(path):
            with contextlib.suppress(OSError):
                path.unlink()
            return None
        obj = json.loads(path.read_text())
        if not isinstance(obj, dict):
            # Syntactically valid JSON but not an object (a bare list/string/
            # number) -- the `dict[str, Any]` annotation on this call used to
            # just trust that shape, so a caller's first `.get(...)` on the
            # result would crash with AttributeError instead of getting the
            # same clean "corrupt, treat as miss" handling a JSONDecodeError
            # already gets.
            logger.warning("placement cache file for %r is not a JSON object "
                            "(got %s) -- treating as corrupt", state_id, type(obj).__name__)
            return None
        return obj
    except (OSError, json.JSONDecodeError) as e:
        logger.warning("placement cache load failed for %r: %s", state_id, e)
        return None


def _find_state_file(state_id: str) -> Path | None:
    """Locate <state_id>.json across all shard subdirectories.

    O(num_shards) ``exists()`` syscalls; no file reads or parses. The
    state_id is validated as 16-hex by the caller, so the join is safe.
    """
    d = cache_dir()
    if not d.exists():
        return None
    fname = f"{state_id}.json"
    for shard in d.iterdir():
        if not shard.is_dir():
            continue
        candidate = shard / fname
        if candidate.exists():
            return candidate
    return None


def find_latest_for_schematic(schematic_path: str) -> dict[str, Any] | None:
    """Return the most recently saved state for this schematic path,
    or None if none exists. Useful for cluster_id stability across
    iterations: ``suggest`` calls this to feed previous_partition.

    Falls back to the next-newest candidate if the most-recent file is
    unreadable/corrupt — a partially-written file from a crashed save
    shouldn't blind the entire stability mechanism."""
    if not schematic_path:
        return None
    candidates = _states_for_schematic(schematic_path)
    if not candidates:
        return None
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    for i, candidate in enumerate(candidates):
        try:
            obj: dict[str, Any] = json.loads(candidate.read_text())
        except (OSError, json.JSONDecodeError) as e:
            logger.warning("Cached state %s is unreadable/corrupt (%s); "
                            "falling back to the next-newest candidate",
                            candidate, e)
            continue
        if i > 0:
            # The caller asked for the LATEST state (cluster_id stability
            # depends on it); silently returning a STALE one with no signal
            # meant "latest" was corrupt used to be indistinguishable from
            # actually getting the latest.
            logger.warning("Most recent cached state(s) for %s were unreadable; "
                            "returning stale candidate %s instead", schematic_path, candidate)
        return obj
    return None


def clear_cache(schematic_path: str | None = None) -> int:
    """Delete cached states. With no path, clears everything; with a
    path, clears only states for that schematic. Returns the number of
    files deleted."""
    d = cache_dir()
    if not d.exists():
        return 0
    count = 0
    failed = 0
    candidates = d.glob("*/*.json") if schematic_path is None else _states_for_schematic(schematic_path)
    for path in candidates:
        try:
            path.unlink()
            count += 1
        except OSError:
            failed += 1
    if failed:
        # bare `contextlib.suppress(OSError)` previously gave the caller no
        # way to tell "5 states, all deleted" from "5 states, only 3
        # deleted" -- the return value already answers the first half
        # (count of successes); this makes the second half visible too.
        logger.warning("clear_cache: %d file(s) could not be deleted "
                        "(schematic_path=%r)", failed, schematic_path)
    return count


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _states_for_schematic(schematic_path: str) -> list[Path]:
    """All cached state files for this schematic — just a directory listing,
    no JSON parsing. O(states_for_this_schematic), not O(total_states)."""
    shard = _shard_dir(schematic_path)
    if not shard.exists():
        return []
    return list(shard.glob("*.json"))


def _evict_lru_for_schematic(schematic_path: str) -> None:
    """Keep at most MAX_STATES_PER_SCHEMATIC states for this schematic."""
    if not schematic_path:
        return
    states = _states_for_schematic(schematic_path)
    if len(states) <= MAX_STATES_PER_SCHEMATIC:
        return
    states.sort(key=lambda p: p.stat().st_mtime)
    failed = 0
    for path in states[: len(states) - MAX_STATES_PER_SCHEMATIC]:
        try:
            path.unlink()
        except OSError:
            failed += 1
    if failed:
        # Called from save_state (fire-and-forget, no return value the
        # caller inspects) -- a failed eviction previously left no trace
        # anywhere, so a schematic could silently accumulate more than
        # MAX_STATES_PER_SCHEMATIC files with nothing to explain why.
        logger.warning("Failed to evict %d stale cache file(s) for %s",
                        failed, schematic_path)


def _sweep_expired(max_age_days: int = DEFAULT_MAX_AGE_DAYS) -> None:
    """Drop any cache file older than the expiry window. Walks all shards."""
    d = cache_dir()
    if not d.exists():
        return
    cutoff = time.time() - max_age_days * 86400
    failed = 0
    for path in d.glob("*/*.json"):
        try:
            if path.stat().st_mtime < cutoff:
                path.unlink()
        except OSError:
            failed += 1
    if failed:
        # Called from save_state (fire-and-forget) -- previously a `pass`
        # with zero signal; a stat/unlink failure here (permission,
        # concurrent delete) used to leave no trace of why expired files
        # keep accumulating.
        logger.warning("Failed to sweep %d expired cache file(s)", failed)


def _expired(path: Path, max_age_days: int = DEFAULT_MAX_AGE_DAYS) -> bool:
    try:
        age_s = time.time() - path.stat().st_mtime
        return age_s > max_age_days * 86400
    except OSError:
        return False
